# Base image
FROM controller_updated:v2

# Set environment variable to disable prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Expose SSH port
EXPOSE 22 80



# Set up SSH server
RUN mkdir /var/run/sshd && echo "root:root" | chpasswd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config



# Start SSH service
CMD ["/usr/sbin/sshd", "-D"]