# playbooks/web_scan.yml
---
- name: Web Application Security Audit
  hosts: dvwa
  become: yes
  
  tasks:
    - name: Check Web Server Status
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}"
        method: GET
        return_content: yes
      register: web_status
      ignore_errors: yes

    - name: Test Common Web Vulnerabilities
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}/{{ item }}"
        method: GET
        return_content: yes
      loop:
        - "login.php"
        - "setup.php"
        - "phpinfo.php"
        - "config/config.inc.php"
      register: vulnerability_test
      ignore_errors: yes

    - name: Check SSL/TLS Configuration
      ansible.builtin.command: "nmap --script ssl-enum-ciphers -p 443 {{ inventory_hostname }}"
      register: ssl_check
      ignore_errors: yes
      when: ssl_enabled | default(true)

    - name: Test SQL Injection Points
      ansible.builtin.uri:
        url: "http://{{ inventory_hostname }}/vulnerabilities/sqli/"
        method: POST
        body: "id=' OR '1'='1"
        body_format: raw
      register: sqli_test
      ignore_errors: yes
