services:
    ubuntu-container:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
        - "${S_SSH_PORT}:22"  # Map SSH to host port 2222
      container_name: ubuntu-ready-container