networks:
  custom_network_client:
    external: true

services:
  ubuntu-container:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2222:22"  # Mappe le port SSH du conteneur au port 2222 de l'hôte
    container_name: ubuntu-ready-container
    networks:
      custom_network_client:
        ipv4_address: ${S_CONTAINER_IP}  # IP fixe sur le premier réseau
     
