networks:
  custom_network_client:
    external: true

services:
  ubuntu-container:
    privileged: true
    image: ubuntu-test:v11.01
    ports:
      - "2227:22"  # Mappe le port SSH du conteneur au port 2222 de l'hôte
    container_name: ubuntu-ontroller2
    networks:
      custom_network_client:
        ipv4_address: ${S_CONTAINER2_IP}  # IP fixe sur le premier réseau
     
