# Base image
FROM ubuntu:20.04

# Set environment variable to disable prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Update, install necessary packages, and clean up
RUN apt-get update && apt-get install -y \
    iputils-ping \
    net-tools \
    openssh-server \
    python3.8 \
    python3-pip && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Set up SSH server
RUN mkdir /var/run/sshd && echo "root:root" | chpasswd && \
    sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Expose SSH port
EXPOSE 22

# Start SSH service
CMD ["/usr/sbin/sshd", "-D"]