networks:
  custom_network_client:
    external: true

services:
  ansible-runner:
    privileged: true
    build:
      context: .  # Contexte racine
      dockerfile: Dockerfile
    working_dir: /ansible-config
    ports:
      - "2228:22"  # Mappe le port SSH du conteneur au port 2228 de l'hôte
    container_name: ubuntu-container2
    networks:
      custom_network_client:
        ipv4_address: ${S_CONTAINER2_IP}  # IP fixe à définir dans un fichier .env
    environment:
      ANSIBLE_HOST_KEY_CHECKING: "False"  # Désactive la vérification des clés SSH
