networks:
  custom_network_client:
    external: true

services:
  controler2:
    privileged: true  # Nécessaire si votre conteneur a besoin d'un accès root pour certaines tâches
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /ansible-config
    ports:
      - "2228:22"  # Mappe le port SSH du conteneur au port 2228 de l'hôte
    container_name: controler2
    networks:
      custom_network_client:
        ipv4_address: ${S_CONTAINER2_IP}  # IP fixe à définir dans un fichier .env
    command: /ansible-config/entrypoint.sh && sleep infinity
    environment:
      ANSIBLE_HOST_KEY_CHECKING: "False"  # Variable d'environnement pour désactiver la vérification des clés SSH