FROM controller_updated:v2

# Expose the required ports
EXPOSE 22 80

RUN echo "root:root" | chpasswd

# Copy the bash script and make it executable
COPY setup_ssh.sh /setup_ssh.sh
RUN chmod 777 /setup_ssh.sh

# Start Apache (DVWA) and SSH services
CMD ["/bin/bash", "-c", s"/usr/sbin/sshd -D && wait"]
