FROM dvwa_11_01_17h_21

# Expose the required ports
EXPOSE 22 80

RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
    sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config

# Copy the bash script and make it executable
COPY setup_ssh.sh /setup_ssh.sh
RUN chmod 777 /setup_ssh.sh

# Start Apache (DVWA) and SSH services
CMD /setup_ssh.sh