networks:
  custom_network_client:
    external: true

services:
  dvwa:
    build: .
    ports:
      - "${C_SSH_PORT}:22"    # Map container SSH port to host port 2223
      - "${C_WEB_PORT}:80"      # Map container web app port to host port 83
    volumes:
      - ./data:/var/www/html  # Optional: Persist DVWA data if needed
    container_name: dvwa_container
    networks:
      custom_network_client:
        ipv4_address: ${C_CONTAINER_IP}  # Adresse IP statique pour ce service