#Run with : docker-compose up --build (Construire et démarrer tous les conteneurs)
version: '3'
services:
  nikto:
    build:
      context: ./docker/nikto
    container_name: nikto_scanner
    entrypoint: ["nikto", "-h", "http://example.com"]

  nmap:
    build:
      context: ./docker/nmap
    container_name: nmap_scanner
    entrypoint: ["nmap", "-sP", "192.168.10.0/24"]

  openvas:
    build:
      context: ./docker/openvas
    container_name: openvas_scanner
    entrypoint: ["openvas", "--scan-target", "192.168.10.10"]

  zap:
    build:
      context: ./docker/zap
    container_name: zap_scanner
    entrypoint: ["zap-cli", "quick-scan", "http://example.com"]
