Vagrant.configure("2") do |config|
    
    # Configuration du pare-feu pfSense
    config.vm.define "firewall" do |firewall|
      config.vm.box = "hichemlamine/pfsense-2.7.2"
      config.vm.box_version = "2.7.2"
      firewall.vm.network "private_network", type: "dhcp", virtualbox__intnet: "net_wan", auto_config: false
      firewall.vm.network "private_network", type: "dhcp", virtualbox__intnet: "net_server", auto_config: false
      firewall.vm.network "private_network", type: "dhcp", virtualbox__intnet: "net_client", auto_config: false
    end
  
    # Configuration du serveur de scan
    config.vm.define "server" do |server|
      server.vm.box = "ubuntu/bionic64"
      server.vm.network "private_network", ip: "192.168.10.10", virtualbox__intnet: "net_server"
      server.vm.provision "ansible" do |ansible|
        ansible.playbook = "../Ansible/playbooks/server_setup.yml"
        ansible.inventory_path = "../Ansible/inventory"
      end
    end
  
    # Configuration de l'ordinateur client
    config.vm.define "client" do |client|
      client.vm.box = "ubuntu/bionic64"
      client.vm.network "private_network", ip: "192.168.20.10", virtualbox__intnet: "net_client"
    end
  end
  