version: '3.8'

services:
  dvwa:
    image: vulnerables/web-dvwa
    ports:
      - "8075:80"  # Mappe le port 80 (web) du conteneur vers le port 8075 de l'hôte
      - "2222:22"  # Mappe le port SSH du conteneur (22) vers le port 2222 de l'hôte
    environment:
      MYSQL_USER: root       # Utilisateur MySQL
      MYSQL_PASS: password   # Mot de passe MySQL
      MYSQL_DB: dvwa         # Nom de la base de données
    restart: always          # Redémarre automatiquement en cas d'échec

  metasploit:
    image: metasploitframework/metasploit-framework
    ports:
      - "4444:4444"          # Mappe le port 4444 pour Metasploit
      - "55553:55553"        # Port secondaire pour Metasploit
    tty: true
    stdin_open: true         # Permet une session interactive avec Metasploit
