---
- name: Complete Port Scan with Ansible
  hosts: vulnerable_containers
  become: yes
  gather_facts: yes

  tasks:
    - name: Port Scanning with Ansible (multiple ports)
      ansible.builtin.wait_for:
        host: "{{ inventory_hostname }}"
        port: "{{ item }}"
        timeout: 2
        state: started
      register: port_scan_results
      loop:
        - 21  # FTP
        - 22  # SSH
        - 23  # Telnet
        - 25  # SMTP
        - 80  # HTTP
        - 443 # HTTPS
        - 3306 # MySQL
        - 6379 # Redis
        - 8080 # HTTP Alternative
      ignore_errors: yes

    - name: Generate Scan Report
      ansible.builtin.debug:
        msg: |
          Port Scan Report for {{ inventory_hostname }}:
          {% for result in port_scan_results.results %}
          Port {{ result.item }}:
          {% if result.failed %}
            - Status: Closed
          {% else %}
            - Status: Open
          {% endif %}
          {% endfor %}
      delegate_to: localhost

    - name: Store Network Scan Results
      ansible.builtin.copy:
        content: |
          Port Scan Results for {{ inventory_hostname }}:
          {% for result in port_scan_results.results %}
          Port {{ result.item }}:
          {% if result.failed %}
            - Status: Closed
          {% else %}
            - Status: Open
          {% endif %}
          {% endfor %}
        dest: "/tmp/complete_net_scan_{{ inventory_hostname }}.log"
      delegate_to: localhost